defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  - scope:
      path: ""
    values:
      layout: "default"

title: "YJG's Think Tank"

permalink: /:categories/:title/

gems:
  - jekyll-paginate-v2
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

algolia:
   application_id: CQTULIJON9
   index_name: yjg30737githubpage_index
   search_only_api_key: 02e41c5d34fc1ace286382b8a6bed586

pagination:
  enabled: true
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  
  trail: 
    before: 2
    after: 2