defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  - scope:
      path: ""
    values:
      layout: "default"

title: "YJG's Think Tank"
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2
pagination:
  
  # Site-wide kill switch, disabled here it doesn't run at all 
  enabled: true

  per_page: 10

  category: 'posts'

  indexpage: 'index'
  
  trail: 
    before: 2
    after: 2