title: "YJG's Think Tank"

permalink: /:categories/:title/
    
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  sort_field: 'date'
  sort_reverse: true
  
  trail: 
    before: 2
    after: 2